#ifndef __FONT_H_INCLUDED__
#define __FONT_H_INCLUDED__

#include <glm/ext/vector_float2.hpp>
#include <glm/ext/vector_int2.hpp>
#include <map>

#include <ft2build.h>
#include FT_FREETYPE_H

/**
 * Represents a glyph generated by FreeType.
 */
struct Glyph 
{
    unsigned int textureID;  // ID handle of the glyph texture
    glm::ivec2   size;       // Size of glyph
    glm::ivec2   bearing;    // Offset from baseline to left/top of glyph
    int advance;             // Offset to advance to next glyph
};

/**
 * Font wrapper responsible for loading and storing glyph data.
 */
class Font
{
public:
    /**
     * Loads a font and generates ASCII glyph textures.
     * @param ft FreeType library handle.
     * @param file Font file path.
     * @param _size Font size in pixels.
     */
    void Load(FT_Library ft, const char* file, unsigned int _size);

    /**
     * Returns the glyph associated with the specified character.
     */
    Glyph GetGlyph(char c) const { return glyphs.at(c); }
    /**
     * Returns the font size in pixels.
     */
    unsigned int GetSize() const { return size; }

private:
    // Generated ASCII glyphs indexed by character.
    std::map<char, Glyph> glyphs;

    unsigned int size = 0;
};

#endif // __FONT_H_INCLUDED__